export const ROUTES = {
  HOME: "/",
  EVENTS: "/events",
  SCHEDULE: "/schedule",
  ACCOMMODATION: "/accommodation",
  TEAM: "/team",
  OUR_SPONSORS: "/our-sponsors",
  CONTACT_US: "/contact-us",
  PROFILE: "/profile",
  LOGIN: "/login",
  ABOUT_US: "/about-us",
  PAYMENT: "/payment",
  ACCOMMODATION_PAYMENT: "/accommodation-payment",
  MERCHANDISE: "/merchandise",
  TERMS: "/terms",
  CANCELLATION_POLICY: "/cancellation-policy",
  PRIVACY_POLICY: "/privacy-policy",
  DELIVERY_POLICY: "/delivery-policy",
  
 //Optional
  AI_SUPPORT: "/ai-support",     
  STICKY_NOTES: "/sticky-notes",  
  GAME_PAGE: "/games",
  MS_PAINT: "/ms-paint",
  MINESWEEPER: "/minesweeper",
  PURPLE_PALACE: "/purple-palace",
  TIC_TAC_TOE: "/tic-tac-toe",
};

export const ROUTE_INFO = [
  {
    id: "ROUTE_HOME",
    name: "Home",
    icon: <Home />,
    path: ROUTES.HOME,
  },
  {
    id: "ROUTE_EVENTS",
    name: "Events",
    icon: <Compass />,
    path: ROUTES.EVENTS,
  },
  {
    id: "ROUTE_SCHEDULE",
    name: "Schedule",
    icon: <CalendarEvent />,
    path: ROUTES.SCHEDULE,
  },
  {
    id: "ROUTE_ACCOMMODATION",
    name: "Accommodation",
    icon: <Bed />,
    path: ROUTES.ACCOMMODATION,
  },
  {
    id: "ROUTE_TEAM",
    name: "Team",
    icon: <Users />,
    path: ROUTES.TEAM,
  },
  {
    id: "ROUTE_OUR_SPONSORS",
    name: "Sponsors",
    icon: <PigMoney />,
    path: ROUTES.OUR_SPONSORS,
  },
  {
    id: "ROUTE_CONTACT_US",
    name: "Contact Us",
    icon: <PhoneCall />,
    path: ROUTES.CONTACT_US,
  },
  {
    id: "ROUTE_PROFILE",
    name: "Profile",
    icon: <UserAvatar />,
    path: ROUTES.PROFILE,
  },
  {
    id: "ROUTE_LOGIN",
    name: "Login/Signup",
    icon: <UserAvatar />,
    path: ROUTES.LOGIN,
  },
  {
    id: "ROUTE_ABOUT_US",
    name: "About Us",
    icon: <InfoCircle />,
    path: ROUTES.ABOUT_US,
  },
  {
    id: "ROUTE_PAYMENT",
    name: "Payment",
    icon: <CreditCard />,
    path: ROUTES.PAYMENT,
  },
  {
    id: "ROUTE_ACCOMMODATION_PAYMENT",
    name: "Accommodation Payment",
    icon: <CreditCard />,
    path: ROUTES.ACCOMMODATION_PAYMENT,
  },
  {
    id: "ROUTE_MERCHANDISE",
    name: "Merchandise",
    icon: <ShoppingBag />,
    path: ROUTES.MERCHANDISE,
  },
  {
    id: "ROUTE_TERMS",
    name: "Terms and Conditions",
    path: ROUTES.TERMS,
  },
  {
    id: "ROUTE_PRIVACY_POLICY",
    name: "Privacy Policy",
    path: ROUTES.PRIVACY_POLICY,
  },
  {
    id: "ROUTE_CANCELLATION_POLICY",
    name: "Cancellation Policy",
    path: ROUTES.CANCELLATION_POLICY,
  },
  {
    id: "ROUTE_DELIVERY_POLICY",
    name: "Delivery Policy",
    path: ROUTES.DELIVERY_POLICY,
  },
  // Optional routes
  {
    id: "ROUTE_AI_SUPPORT",
    name: "AI Support",
    icon: <Users />,
    path: ROUTES.AI_SUPPORT,
  },
  {
    id: "ROUTE_STICKY_NOTES",
    name: "Sticky Notes",
    icon: <StickyNote />,
    path: ROUTES.STICKY_NOTES,
  },
  {
    id: "ROUTE_GAME_PAGE",
    name: "Game Page",
    icon: <Gamepad />,
    path: ROUTES.GAME_PAGE,
  },
  {
    id: "ROUTE_MS_PAINT",
    name: "MS Paint",
    icon: <Palette />,
    path: ROUTES.MS_PAINT,
  },
  {
    id: "ROUTE_MINESWEEPER",
    name: "Minesweeper",
    path: ROUTES.MINESWEEPER,
  },
  {
    id: "ROUTE_PURPLE_PALACE",
    name: "Purple Palace",
    icon: <Memory />,
    path: ROUTES.PURPLE_PALACE,
  },
  {
    id: "ROUTE_TIC_TAC_TOE",
    name: "Tic Tac Toe",
    icon: <TicTacToe />,
    path: ROUTES.TIC_TAC_TOE,
  },
];
